### PR TITLE
fix: Changing platform defaults to chrome/linux for non-edge properties files

### PR DESCRIPTION
**Pull request by mmerrell**

### CODE REVIEW

**Comment by kgress** [comment]
LGTM. @mmerrell , can you please update the commit message to say, "fix: Changing platform defaults to chrome/linux for non-edge properties files". This will trigger a patch release.

**Comment by kgress** [comment]
Also, one other thing:

Could you update the application-sauce_edge.properties to another browser? How about doing a mac/safari? Also renaming it to reflect the change? Using the edge config will error out just like how it is in overrides.

We'll also get the configurations updated in Scaffold so we don't run into this later.

**Comment by mmerrell** [comment]
Should be good now... have a look!

**Review by kgress — APPROVED** [review]
LGTM, thanks for updating this!

**Pull request merged**
